### ISSUE TITLE
Replace <span> with <font> to avoid reseting font-family

### ISSUE THREAD

**Issue by msaraiva** [tmbb/makeup#21]
When converting the generated HTML to EPUB, the `font-family` information is lost. Here's an example from the Ecto documentation:

![image](https://user-images.githubusercontent.com/457237/59512320-dca7de80-8e8e-11e9-9d4a-0c4ea1a28ec0.png)

The font for `<code>` should be monospaced in both cases but it only works for the html version on the left.

I've tried to set the `font-family` for the `<span>` nodes in [makeup.less](https://github.com/elixir-lang/ex_doc/blob/v0.20.2/assets/less/makeup.less) and even tried to set it inline using `style`. It worked for things like `color` and `font-size` but not for the `font-family`. Maybe somebody with better css skills might figure out a way to do that.

Apparently, using `<font>` instead of `<span>` [here](https://github.com/msaraiva/makeup/blob/v0.5.0/lib/makeup/formatters/html/html_formatter.ex#L18-L25) fixes the issue without messing with the html version:

![image](https://user-images.githubusercontent.com/457237/59512815-e0883080-8e8f-11e9-835e-b2699702ea4e.png)

Now, with `<font>,` the epub version uses the monospaced font as expected:

![image](https://user-images.githubusercontent.com/457237/59513089-7e7bfb00-8e90-11e9-87cd-97fd3c420f80.png)

In case there's no other solution and you think this should be addressed this way, let me know. I'll be glad to create a PR.

Cheers.

**Comment by josevalim** [comment]
Unfortunately the `font` tag is deprecated. But any other inline tag works, as long as it does not have a default markup (for example, `em` wouldn't work because we can't remove the italic). My suggestion is to make this an option in `makeup` and then we can change ExDoc to use any of the new tags. I would use the `samp` tag, it is not the most semantically precise but unfortunately we don't have any option on this matter.

**Comment by tmbb** [comment]
> My suggestion is to make this an option in makeup and then we can change ExDoc to use any of the new tags.

You can write a new formatter *right now* that uses whatever tag you want instead of the `<span>` tag. But I can add support for other tags directly in the default formatter too.

**Comment by josevalim** [comment]
@tmbb we would like to keep everything as is, except the tag, so what about a `:tag` option that defaults to `:span`?

**Comment by tmbb** [comment]
That sounds good to me. But that would require adding new options to ExDoc so that ExDoc could feed that option into Makeup.

**Comment by tmbb** [comment]
Maybe a config option like:

```
docs: [
  # ...
  tag: fn :epub -> "samp"; :html -> "span" end,
  # ...
]
```

**Comment by josevalim** [comment]
@tmbb i was not planning to expose it to users but rather something internal. I was also thinking about using "samp" across the board. It is less work/code. Thoughts?

**Comment by tmbb** [comment]
> @tmbb i was not planning to expose it to users but rather something internal.

Ok, that's trivial then.

>  I was also thinking about using "samp" across the board. It is less work/code. Thoughts?

I have no problem with that. I can add support for different tags and release a `0.9.0` version and make ExDoc dependent on that version. That way, ExDoc will depend on a Makeup version which already supports the lexer registry, so that you can add new lexers to the deps to support more programming languages (this would be much cooler if I had actually written some complete lexers besides the Elixir one, but I've been busy with other things)

**Comment by josevalim** [comment]
Sounds great. We will try to get a PR going, thanks! :)

**Comment by msaraiva** [comment]
Awesome. I'll start working on it!

**Comment by josevalim** [comment]
Btw, I just noticed that elixir-lang.org ebooks have the same problem, so once the fix is merged, I will move Elixir ebooks to also use makeup. :D
